# Changing any of the "actively-remove" options to true will have permament effect on your worlds.
# Proceed with caution.
villagers:
  deny-spawn: false
  actively-remove: false
mending:
  actively-remove: false